version: '3.5'
services:
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    restart: always
    ports:
      - '5672:5672'
      - '8083:15672'
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: test
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

  fakesmtp:
    image: gessnerfl/fake-smtp-server
    container_name: fakesmtp
    restart: always
    hostname: fakesmtp
    ports:
      - '5025:5025'
      - '8084:5080'

  mongodb:
    image: mongo
    restart: always
    container_name: readme.notifier.mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: readme-notifier
    ports:
      - 27018:27017
    volumes:
      - ./db:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/typoteka-notify --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  mongodb-express:
    image: mongo-express
    restart: always
    container_name: readme.notifier.mongo-express
    ports:
      - 8080:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://admin:test@mongodb:27017/
