-- AlterTable
ALTER TABLE "Post" ALTER COLUMN "isPublished" SET DEFAULT true,
ALTER COLUMN "likes" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "tags" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "isRepost" SET DEFAULT false;
