# New user registration
POST http://localhost:4444/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "address@domain.domaim",
  "name": "User",
  "password": "p4ssw0rdDd"
}

###

# Login user by email and password
POST http://localhost:4444/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "address@domain.domaim",
  "password": "p4ssw0rdDd"
}

###
