# Create user

POST http://localhost:3333/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "user@notfound.local",
  "firstname": "Keks",
  "lastname": "Smith",
  "password": "123456",
  "avatar": "avatar.png"
}

###

# Get user by ID
GET http://localhost:3333/api/auth/3da19fca-7001-4bb0-8cec-d5306564fb21 HTTP/1.1

###

# Login user by email and password
POST http://localhost:3333/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "user@notfound.local",
  "password": "123456"
}

###
